@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1
@USER_ID=12345
### POST register:
POST {{BASE_URL}}/auth/register
content-type: application/json

{
    "username": "Teresa",
    "email": "teresa@gmail.com",
    "password": "veryStrongPassword1"
}

### POST register:
POST {{BASE_URL}}/auth/register
content-type: application/json

{
    "username": "Trunt",
    "email": "trunts@gmail.com",
    "password": "veryStrongPassword2"
}


### POST login:
POST {{BASE_URL}}/auth/login
content-type: application/json

{
    "username": "Teresa",
    "email": "teresa@gmail.com",
    "password": "veryStrongPassword1"
}

### POST forgot:
POST {{BASE_URL}}/auth/forgotpassword
content-type: application/json

{
    "username": "Teresa",
    "email": "teresa@gmail.com",
    "password": "veryStrongPassword1"
}

### POST reset:
POST {{BASE_URL}}/auth/passwordreset
content-type: application/json

{
    "username": "Teresa",
    "email": "teresa@gmail.com",
    "password": "veryStrongPassword1"
}


#### Get ALL:
GET {{BASE_URL}}/auth/users

### GET by :id: 
GET {{BASE_URL}}/auth/users/{{USER_ID}}

### PUT by :id:
PUT {{BASE_URL}}/auth/users/{{USER_ID}}
content-type: application/json

{
    "username": "Teresa",
    "email": "teresa@gmail.com",
    "password": "veryStrongPassword1"
}

### PATCH by :id:
PATCH {{BASE_URL}}/auth/users/{{USER_ID}}
content-type: application/json

{
    "username": "Cheburashka"
}

### 5. DELETE by :id  
DELETE {{BASE_URL}}/auth/users/{{USER_ID}}