@BASE_URL=http://localhost:{{$dotenv PORT}}/api/v1/auth
@USER_ID=12345
@resetToken = 70b15890d9641b508772e8aebf0a44349c03abcb
### POST register:
POST {{BASE_URL}}/register
content-type: application/json

{
    "username": "Cheburashka",
    "email": "kosmolet.git@gmail.com",
    "password": "veryStrongPassword1"
}

### POST login:
POST {{BASE_URL}}/login
content-type: application/json

{
    "email": "kosmolet.git@gmail.com",
    "password": "veryStrongPassword1"
}

### POST forgot:
POST {{BASE_URL}}/forgotpassword
content-type: application/json

{
    "email": "kosmolet.git@gmail.com"
}

### POST reset:
POST {{BASE_URL}}/resetpassword/{{resetToken}}
content-type: application/json

{
    "password": "veryStrongPassword2"
}
 